# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: P:/18summer/engs031/G19/Etch-a-Sketch/Etch-a-Sketch.srcs/sources_1/ip/Block_Ram/Block_Ram.xci
# IP: The module: 'Block_Ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: p:/18summer/engs031/G19/Etch-a-Sketch/Etch-a-Sketch.srcs/sources_1/ip/Block_Ram/Block_Ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: P:/18summer/engs031/G19/Etch-a-Sketch/Etch-a-Sketch.srcs/sources_1/ip/Block_Ram/Block_Ram.xci
# IP: The module: 'Block_Ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: p:/18summer/engs031/G19/Etch-a-Sketch/Etch-a-Sketch.srcs/sources_1/ip/Block_Ram/Block_Ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
